<Project>
  <PropertyGroup>
    <Version>3.0</Version>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <FileVersion>3.0.0.0</FileVersion>
    <Product>Bili Downloader Lite</Product>
    <Copyright>Qrzzzz and contributors</Copyright>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Deterministic>true</Deterministic>
    <InformationalVersion>$(Version)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="GitCommit" Value="$(SourceRevisionId)" />
    <AssemblyMetadata Include="BuildDirty" Value="$(BuildDirty)" />
  </ItemGroup>
</Project>
